// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// blinkdma //
// -------- //

#define blinkdma_wrap_target 0
#define blinkdma_wrap 4

static const uint16_t blinkdma_program_instructions[] = {
            //     .wrap_target
    0x80e0, //  0: pull   ifempty block              
    0xe901, //  1: set    pins, 1                [9] 
    0x6901, //  2: out    pins, 1                [9] 
    0xf400, //  3: set    pins, 0                [20]
    0x00e1, //  4: jmp    !osre, 1                   
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program blinkdma_program = {
    .instructions = blinkdma_program_instructions,
    .length = 5,
    .origin = -1,
};

static inline pio_sm_config blinkdma_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + blinkdma_wrap_target, offset + blinkdma_wrap);
    return c;
}
#endif

